name: Build Lively Portable

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish Lively
      run: |
        dotnet publish src/Lively/Lively/Lively.csproj `
          -c Release `
          -r win-x64 `
          --self-contained true `
          -p:PublishSingleFile=false `
          -o publish

    - name: Remove debug symbols
      run: |
        del publish\*.pdb -ErrorAction SilentlyContinue

    - name: Upload Portable Build
      uses: actions/upload-artifact@v4
      with:
        name: Lively-Portable
        path: publish/
