name: Build Full Lively

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore
      run: nuget restore src/Lively/Lively.sln

    - name: Build full solution
      run: msbuild src/Lively/Lively.sln /p:Configuration=Release /p:Platform=x64 /m

    # ✅ Копируем ВСЮ папку net9 Release
    - name: Copy Release Output
      run: |
        mkdir publish
        xcopy src\Lively\Lively\bin\x64\Release\net9.0-windows* publish\ /E /I /Y

    # ✅ Удаляем debug мусор
    - name: Remove debug symbols
      run: |
        del publish\*.pdb /S /Q

    - name: Upload full portable build
      uses: actions/upload-artifact@v4
      with:
        name: Lively-Portable
        path: publish/
